base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from base import urls_api
from invoices.views import index_view

urlpatterns = [
    path("", index_view, name="index"),
    path("admin/", admin.site.urls),
    path("api/", include(urls_api)),
    path("api-token-auth/", obtain_auth_token),
    path("companies/", include("companies.urls")),
    path("countries/", include("countries.urls")),
    path("currencies/", include("currencies.urls")),
    path("invoices/", include("invoices.urls")),
    path("items/", include("items.urls")),
    path("users/", include("users.urls")),
    path("vat_rates/", include("vat_rates.urls")),
    path("reports/", include("reports.urls")),
    path("accountants/", include("accountants.urls")),
    path("summary_recipients/", include("summary_recipients.urls")),
    path("persons/", include("persons.urls")),
    path("faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="privacy_policy.html"),
        name="privacy_policy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/urls.py
from django.urls import path

from companies.views import (
    create_company_ajax_view,
    create_company_view,
    delete_company_view,
    detail_company_view,
    list_companies_view,
    replace_company_view,
    settings_company_view,
)

app_name = "companies"
urlpatterns = [
    path("", list_companies_view, name="list_companies"),
    path(
        "my_companies/",
        list_companies_view,
        name="list_my_companies",
        kwargs={"my_companies": True},
    ),
    path("<int:company_id>/", detail_company_view, name="detail_company"),
    path("create/", create_company_view, name="create_company"),
    path("create_ajax/", create_company_ajax_view, name="create_company_ajax"),
    path(
        "create_my_company/",
        create_company_view,
        name="create_my_company",
        kwargs={"create_my_company": True},
    ),
    path(
        "create_my_company_ajax/",
        create_company_ajax_view,
        name="create_my_company_ajax",
        kwargs={"create_my_company": True},
    ),
    path("replace/<int:company_id>/", replace_company_view, name="replace_company"),
    path("delete/<int:company_id>/", delete_company_view, name="delete_company"),
    path(
        "<int:company_id>/settings_company/",
        settings_company_view,
        name="settings_company",
    ),
]

invoice_manager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

summary_recipients/urls.py
from django.urls import path

from summary_recipients.views import (
    create_summary_recipient_view,
    delete_summary_recipient_view,
    list_summary_recipients_view,
    replace_summary_recipient_view,
)

app_name = "summary_recipients"
urlpatterns = [
    path(
        "<int:company_id>/summary_recipients/",
        list_summary_recipients_view,
        name="list_summary_recipients",
    ),
    path(
        "<int:company_id>/summary_recipient/create/",
        create_summary_recipient_view,
        name="create_summary_recipient",
    ),
    path(
        "summary_recipient/delete/<int:summary_recipient_id>/",
        delete_summary_recipient_view,
        name="delete_summary_recipient",
    ),
    path(
        "summary_recipient/replace/<int:summary_recipient_id>/",
        replace_summary_recipient_view,
        name="replace_summary_recipient",
    ),
]

summary_recipients/models.py
from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.utils.translation import gettext_lazy as _

from companies.models import Company


class SummaryRecipient(models.Model):
    MONTHLY = 0
    QUARTERLY = 1

    SETTLEMENT_TYPES = (
        (MONTHLY, _("Monthly")),
        (QUARTERLY, _("Quarterly")),
    )

    description = models.CharField(verbose_name=_("Description"), max_length=50)
    company = models.ForeignKey(
        Company,
        verbose_name=_("Company"),
        on_delete=models.CASCADE,
        related_name="summary_recipients",
    )
    day = models.PositiveIntegerField(verbose_name=_("Day of send"))
    email = models.EmailField(_("Email"))
    settlement_types = models.IntegerField(
        verbose_name=_("Settlement types"), choices=SETTLEMENT_TYPES
    )
    final_call = models.BooleanField(verbose_name=_("Final call"), default=False)
    is_last_day = models.BooleanField(
        verbose_name=_("Last day in month"), default=False
    )

    class Meta:
        verbose_name_plural = _("summary recipients")

    def __str__(self):
        return self.description

    def send_email(self, subject, content, files=None):
        email = EmailMessage(
            subject,
            content,
            settings.EMAIL_SENDER,
            [self.email],
        )

        if files:
            for data in files:
                email.attach(data["name"], data["content"])

        return email.send()

summary_recipients/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from base.validators import max_day_validator
from summary_recipients.models import SummaryRecipient

LAST_DAYS_OF_MONTH = [28, 29, 30, 31]


class SummaryRecipientForm(forms.ModelForm):
    class Meta:
        model = SummaryRecipient
        fields = [
            "description",
            "day",
            "email",
            "settlement_types",
            "final_call",
            "is_last_day",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.fields:
            if field in ["final_call", "is_last_day"]:
                continue
            self.fields[field].widget.attrs["class"] = "form-control"

        day_field: forms.IntegerField = self.fields["day"]
        day_field.validators = [max_day_validator]

    def clean_day(self):
        day = self.cleaned_data.get("day")
        is_last_day = self.data.get("is_last_day")

        if is_last_day and day not in LAST_DAYS_OF_MONTH:
            raise forms.ValidationError(_("This field is not last day of month."))

        return day

summary_recipients/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from summary_recipients.forms import SummaryRecipientForm
from summary_recipients.models import SummaryRecipient
from summary_recipients.utils import (
    get_user_company_or_404,
    get_user_summary_recipient_or_404,
)


@login_required
def list_summary_recipients_view(request, company_id):
    company = get_user_company_or_404(company_id, request.user)
    summary_recipients = SummaryRecipient.objects.filter(
        company=company
    ).select_related("company")

    context = {"company": company, "summary_recipients": summary_recipients}
    return render(request, "summary_recipients/list_summary_recipients.html", context)


@login_required
def create_summary_recipient_view(request, company_id):
    company = get_user_company_or_404(company_id, request.user)

    if request.method != "POST":
        form = SummaryRecipientForm()
    else:
        form = SummaryRecipientForm(data=request.POST)
        if form.is_valid():
            month_summary_recipient = form.save(commit=False)
            month_summary_recipient.company = company
            month_summary_recipient.save()
            return redirect("summary_recipients:list_summary_recipients", company.pk)

    context = {"form": form, "company": company}
    return render(request, "summary_recipients/create_summary_recipient.html", context)


@login_required
def replace_summary_recipient_view(request, summary_recipient_id):
    summary_recipient = get_user_summary_recipient_or_404(
        summary_recipient_id, request.user
    )

    if request.method != "POST":
        form = SummaryRecipientForm(instance=summary_recipient)
    else:
        form = SummaryRecipientForm(instance=summary_recipient, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(
                "summary_recipients:list_summary_recipients",
                summary_recipient.company.pk,
            )

    context = {
        "summary_recipient": summary_recipient,
        "form": form,
        "company": summary_recipient.company,
    }
    return render(request, "summary_recipients/replace_summary_recipient.html", context)


@login_required
def delete_summary_recipient_view(request, summary_recipient_id):
    summary_recipient = get_user_summary_recipient_or_404(
        summary_recipient_id, request.user
    )
    summary_recipient.delete()

    return redirect(
        "summary_recipients:list_summary_recipients", summary_recipient.company.pk
    )

templates/summary_recipients/create_summary_recipient.html
{% extends "base.html" %}{% load static %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/js/datepicker-full.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/js/locales/pl.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/css/datepicker-bs5.min.css">
    <script type="text/javascript" src="{% static 'utils.js' %}"></script>
    <script type="text/javascript" src="{% static 'check_last_day.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'companies:list_my_companies' %}">Moje Firmy</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'companies:detail_company' company.pk %}">{{ company.name }}</a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:settings_company' company.pk %}">Ustawienia</a></li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'summary_recipients:list_summary_recipients' company.pk %}">Odbiorcy faktur</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Dodaj</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2">
            <form action="{% url 'summary_recipients:create_summary_recipient' company.pk %}" method='post'>
                {% csrf_token %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.description.label_tag }}</div>
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-center">{{ form.description }}</div>
                </div>
                {% if form.description.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.description.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2" id="dayContainer">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center" style="font-weight: bold;">{{ form.day.label_tag }}</div>
                    <div class="col-12 col-md-2 col-lg-2 d-flex align-items-center">{{ form.day }}</div>
                    <div class="col-12 col-md-3 mt-2 mt-md-0 d-flex align-items-center" style="font-weight: bold;">
                        {{ form.is_last_day }}
                        <span class="ms-2 font-weight-bold">{{ form.is_last_day.label_tag|cut:":" }}</span></div>
                </div>
                <div id="id_last_day_errors_container">
                    {% if form.day.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.day.errors }}</div>
                    </div>
                {% endif %}
                </div>
                {% if form.is_last_day.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.is_last_day.errors }}</div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.email.label_tag }}</div>
                    <div class="col-12 col-md-5 col-lg-4 d-flex align-items-center">{{ form.email }}</div>
                </div>
                {% if form.email.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.email.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.settlement_types.label_tag }}</div>
                    <div class="col-12 col-md-3 col-lg-2 d-flex align-items-center">{{ form.settlement_types }}</div>
                </div>
                {% if form.settlement_types.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.settlement_types.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">
                        {{ form.final_call.label_tag }}
                    </div>
                    <div class="col-12 col-md-1 d-flex align-items-center">
                        {{ form.final_call }}
                    </div>
                </div>
                {% if form.final_call.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.final_call.errors }}</div>
                    </div>
                {% endif %}
                <div class="row mt-4 justify-content-center">
                    <div class="col-12 col-md-auto d-flex flex-column flex-md-row gap-2">
                        <button class="btn btn-primary w-100 w-md-auto" name="submit">Zapisz</button>
                        <a class="btn btn-secondary w-100 w-md-auto" href="{% url 'summary_recipients:list_summary_recipients' company.pk %}">Powrót</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/summary_recipients/list_summary_recipients.html
{% extends "base.html" %}{% load static %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:list_my_companies' %}">Moje firmy</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:detail_company' company.pk %}">{{ company.name }}</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:settings_company' company.pk %}">Ustawienia</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Odbiorcy faktury</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2">
            {% if summary_recipients %}
                <div class="table-responsive">
                    <table class="table table-hover text-center">
                        <thead class="table-light">
                            <tr>
                                <th>Lp.</th>
                                <th>Opis</th>
                                <th>Dzień wysłania</th>
                                <th>Email</th>
                                <th>Rodzaj rozliczenia</th>
                                <th>Rozliczenie zamykające</th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for summary_recipient in summary_recipients %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ summary_recipient.description }}</td>
                                    <td>{{ summary_recipient.day }}</td>
                                    <td>{{ summary_recipient.email }}</td>
                                    <td>{{ summary_recipient.get_settlement_types_display}}</td>
                                    <td>
                                        {% if summary_recipient.final_call %}
                                            <span>Tak</span>
                                        {% else %}
                                            <span>Nie</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'summary_recipients:replace_summary_recipient' summary_recipient.pk %}">Edytuj</a>
                                        <a href="{% url 'summary_recipients:delete_summary_recipient' summary_recipient.pk %}">Usuń</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-12 d-flex justify-content-left">
                        <b>Brak odbiorcy faktury</b>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="row mt-2">
            <div class="col-12 col-md-auto">
                <a class="btn btn-primary w-100 w-md-auto" href="{% url 'summary_recipients:create_summary_recipient' company.pk %}">Dodaj</a>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-6 d-flex justify-content-center flex-md-row flex-column">
                <a class="btn btn-secondary" href="{% url 'companies:settings_company' company.pk %}">Powrót</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/summary_recipients/replace_summary_recipient.html
{% extends "base.html" %}{% load static %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/js/datepicker-full.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/js/locales/pl.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/css/datepicker-bs5.min.css">
    <script type="text/javascript" src="{% static 'utils.js' %}"></script>
    <script type="text/javascript" src="{% static 'check_last_day.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'companies:list_my_companies' %}">Moje Firmy</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'companies:detail_company' company.pk %}">{{ company.name }}</a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:settings_company' company.pk %}">Ustawienia</a></li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'summary_recipients:list_summary_recipients' company.pk %}">Odbiorcy faktur</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Edycja</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2">
            <form action="{% url 'summary_recipients:replace_summary_recipient' summary_recipient.pk %}" method='post'>
                {% csrf_token %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.description.label_tag }}</div>
                    <div class="col-12 col-md-4 col-lg-3 d-flex align-items-center">{{ form.description }}</div>
                </div>
                {% if form.description.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.description.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2" id="dayContainer">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center" style="font-weight: bold;">{{ form.day.label_tag }}</div>
                    <div class="col-12 col-md-2 col-lg-2 d-flex align-items-center">{{ form.day }}</div>
                    <div class="col-12 col-md-3 mt-2 mt-md-0 d-flex align-items-center" style="font-weight: bold;">
                        {{ form.is_last_day }}
                        <span class="ms-2 font-weight-bold">{{ form.is_last_day.label_tag|cut:":" }}</span></div>
                </div>
                <div id="id_last_day_errors_container">
                    {% if form.day.errors %}
                        <div class="row">
                            <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.day.errors }}</div>
                        </div>
                    {% endif %}
                </div>
                {% if form.is_last_day.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.is_last_day.errors }}</div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.email.label_tag }}</div>
                    <div class="col-12 col-md-5 col-lg-4 d-flex align-items-center">{{ form.email }}</div>
                </div>
                {% if form.email.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.email.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.settlement_types.label_tag }}</div>
                    <div class="col-12 col-md-3 col-lg-2 d-flex align-items-center">{{ form.settlement_types }}</div>
                </div>
                {% if form.settlement_types.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">
                            {{ form.settlement_types.errors }}
                        </div>
                    </div>
                {% endif %}
                <div class="row mb-2">
                    <div class="col-12 col-md-6 d-flex justify-content-md-end align-items-center"
                         style="font-weight: bold;">{{ form.final_call.label_tag }}
                    </div>
                    <div class="col-12 col-md-1 d-flex align-items-center">
                        {{ form.final_call }}
                    </div>
                </div>
                {% if form.final_call.errors %}
                    <div class="row">
                        <div class="col-12 col-md-6 offset-md-6 text-danger">{{ form.final_call.errors }}</div>
                    </div>
                {% endif %}
                <div class="row mt-4 justify-content-center">
                    <div class="col-12 col-md-auto d-flex flex-column flex-md-row gap-2">
                        <button class="btn btn-primary w-100 w-md-auto" name="submit">Zapisz</button>
                        <a class="btn btn-secondary w-100 w-md-auto" href="{% url 'summary_recipients:list_summary_recipients' company.pk %}">Powrót</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}