accountants/urls.py
from django.urls import path

from accountants.views import (
    create_accountant_view,
    delete_accountant_view,
    list_accountants_view,
    replace_accountant_view,
)

app_name = "accountants"
urlpatterns = [
    path(
        "<int:company_id>/accountants/", list_accountants_view, name="list_accountants"
    ),
    path(
        "<int:company_id>/accountant/create/",
        create_accountant_view,
        name="create_accountant",
    ),
    path(
        "accountant/replace/<int:accountant_id>/",
        replace_accountant_view,
        name="replace_accountant",
    ),
    path(
        "accountant/delete/<int:accountant_id>/",
        delete_accountant_view,
        name="delete_accountant",
    ),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from base import urls_api
from invoices.views import index_view

urlpatterns = [
    path("", index_view, name="index"),
    path("admin/", admin.site.urls),
    path("api/", include(urls_api)),
    path("api-token-auth/", obtain_auth_token),
    path("companies/", include("companies.urls")),
    path("countries/", include("countries.urls")),
    path("currencies/", include("currencies.urls")),
    path("invoices/", include("invoices.urls")),
    path("items/", include("items.urls")),
    path("users/", include("users.urls")),
    path("vat_rates/", include("vat_rates.urls")),
    path("reports/", include("reports.urls")),
    path("accountants/", include("accountants.urls")),
    path("summary_recipients/", include("summary_recipients.urls")),
    path("persons/", include("persons.urls")),
    path("faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="privacy_policy.html"),
        name="privacy_policy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/urls.py
from django.urls import path

from companies.views import (
    create_company_ajax_view,
    create_company_view,
    delete_company_view,
    detail_company_view,
    list_companies_view,
    replace_company_view,
    settings_company_view,
)

app_name = "companies"
urlpatterns = [
    path("", list_companies_view, name="list_companies"),
    path(
        "my_companies/",
        list_companies_view,
        name="list_my_companies",
        kwargs={"my_companies": True},
    ),
    path("<int:company_id>/", detail_company_view, name="detail_company"),
    path("create/", create_company_view, name="create_company"),
    path("create_ajax/", create_company_ajax_view, name="create_company_ajax"),
    path(
        "create_my_company/",
        create_company_view,
        name="create_my_company",
        kwargs={"create_my_company": True},
    ),
    path(
        "create_my_company_ajax/",
        create_company_ajax_view,
        name="create_my_company_ajax",
        kwargs={"create_my_company": True},
    ),
    path("replace/<int:company_id>/", replace_company_view, name="replace_company"),
    path("delete/<int:company_id>/", delete_company_view, name="delete_company"),
    path(
        "<int:company_id>/settings_company/",
        settings_company_view,
        name="settings_company",
    ),
]

countries/urls.py
from django.urls import path

from countries.views import (
    create_country_ajax_view,
    create_country_view,
    delete_country_view,
    list_countries_view,
    replace_country_view,
)

app_name = "countries"
urlpatterns = [
    path("", list_countries_view, name="list_countries"),
    path("create/", create_country_view, name="create_country"),
    path("create_ajax/", create_country_ajax_view, name="create_country_ajax"),
    path("replace/<int:country_id>/", replace_country_view, name="replace_country"),
    path("delete/<int:country_id>/", delete_country_view, name="delete_country"),
]

invoice_manager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

invoices/urls.py
from django.urls import path

from invoices.views import (
    create_buy_invoice_view,
    create_sell_invoice_view,
    create_sell_person_invoice_view,
    create_sell_person_to_client_invoice_view,
    delete_invoice_view,
    detail_invoice_view,
    duplicate_company_invoice_view,
    duplicate_individual_invoice_view,
    list_invoices_view,
    pdf_invoice_view,
    replace_buy_invoice_view,
    replace_sell_invoice_view,
    replace_sell_person_to_client_invoice_view,
)

app_name = "invoices"
urlpatterns = [
    path("", list_invoices_view, name="list_invoices"),
    path("<int:invoice_id>/", detail_invoice_view, name="detail_invoice"),
    path("create_sell_invoice/", create_sell_invoice_view, name="create_sell_invoice"),
    path("create_buy_invoice/", create_buy_invoice_view, name="create_buy_invoice"),
    path(
        "create_sell_person_invoice/",
        create_sell_person_invoice_view,
        name="create_sell_person_invoice",
    ),
    path(
        "create_sell_person_to_client_invoice/",
        create_sell_person_to_client_invoice_view,
        name="create_sell_person_to_client_invoice",
    ),
    path(
        "duplicate_company_invoice/<int:invoice_id>/",
        duplicate_company_invoice_view,
        name="duplicate_company_invoice",
    ),
    path(
        "duplicate_individual_invoice/<int:invoice_id>/",
        duplicate_individual_invoice_view,
        name="duplicate_individual_invoice",
    ),
    path(
        "replace_sell_invoice/<int:invoice_id>/",
        replace_sell_invoice_view,
        name="replace_sell_invoice",
    ),
    path(
        "replace_sell_person_to_client_invoice/<int:invoice_id>/",
        replace_sell_person_to_client_invoice_view,
        name="replace_sell_person_to_client_invoice",
    ),
    path(
        "create_correction_invoice/<int:invoice_id>/",
        replace_sell_invoice_view,
        name="create_correction_invoice",
        kwargs={"create_correction": True},
    ),
    path(
        "create_correction_person_to_client_invoice/<int:invoice_id>/",
        replace_sell_person_to_client_invoice_view,
        name="create_correction_person_to_client_invoice",
        kwargs={"create_correction": True},
    ),
    path(
        "replace_buy_invoice/<int:invoice_id>/",
        replace_buy_invoice_view,
        name="replace_buy_invoice",
    ),
    path("delete/<int:invoice_id>/", delete_invoice_view, name="delete_invoice"),
    path("pdf/<int:invoice_id>/", pdf_invoice_view, name="pdf_invoice"),
]

summary_recipients/urls.py
from django.urls import path

from summary_recipients.views import (
    create_summary_recipient_view,
    delete_summary_recipient_view,
    list_summary_recipients_view,
    replace_summary_recipient_view,
)

app_name = "summary_recipients"
urlpatterns = [
    path(
        "<int:company_id>/summary_recipients/",
        list_summary_recipients_view,
        name="list_summary_recipients",
    ),
    path(
        "<int:company_id>/summary_recipient/create/",
        create_summary_recipient_view,
        name="create_summary_recipient",
    ),
    path(
        "summary_recipient/delete/<int:summary_recipient_id>/",
        delete_summary_recipient_view,
        name="delete_summary_recipient",
    ),
    path(
        "summary_recipient/replace/<int:summary_recipient_id>/",
        replace_summary_recipient_view,
        name="replace_summary_recipient",
    ),
]

companies/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from companies.managers import MyClientsManager
from countries.models import Country
from users.models import User


class Company(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=100)
    nip = models.CharField(verbose_name=_("NIP"), max_length=13)
    regon = models.CharField(
        verbose_name=_("Regon"),
        max_length=14,
        null=True,
    )
    country = models.ForeignKey(
        Country, verbose_name=_("Country"), on_delete=models.CASCADE, null=True
    )
    address = models.CharField(verbose_name=_("Address"), max_length=100)
    zip_code = models.CharField(verbose_name=_("ZIP Code"), max_length=10)
    city = models.CharField(verbose_name=_("City"), max_length=60)
    email = models.EmailField(verbose_name=_("Email"), null=True, blank=True)
    phone_number = models.CharField(
        verbose_name=_("Phone number"), max_length=20, null=True, blank=True
    )
    user = models.ForeignKey(
        User, verbose_name=_("User"), on_delete=models.CASCADE, null=True
    )
    is_my_company = models.BooleanField(
        verbose_name=_("Is my company"), default=False, editable=False
    )

    objects = models.Manager()
    my_clients = MyClientsManager()

    class Meta:
        verbose_name_plural = _("companies")
        ordering = ["name"]
        unique_together = ["nip", "regon", "user"]

    def __str__(self):
        return self.name

companies/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from base.validators import (
    nip_validator,
    phone_number_validator,
    regon_validator,
    zip_code_validator,
)
from companies.models import Company
from countries.models import Country


class CompanyForm(forms.ModelForm):
    next = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Company
        fields = [
            "next",
            "name",
            "nip",
            "regon",
            "country",
            "address",
            "zip_code",
            "city",
            "email",
            "phone_number",
        ]

    def __init__(self, current_user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.current_user = current_user
        self.fields["country"].queryset = Country.objects.filter(
            user=current_user
        ).order_by("country")

        for field in self.Meta.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

        self.fields["nip"].validators = [nip_validator]
        self.fields["regon"].validators = [regon_validator]
        self.fields["zip_code"].validators = [zip_code_validator]
        self.fields["phone_number"].validators = [phone_number_validator]

    def clean_nip(self):
        nip = self.cleaned_data.get("nip")
        company = Company.objects.filter(nip=nip, user=self.current_user)

        if self.instance.pk:
            company = company.exclude(pk=self.instance.pk)

        if company.exists():
            raise forms.ValidationError(_("Nip already exists"))

        return nip

    def clean_regon(self):
        regon = self.cleaned_data.get("regon")
        company = Company.objects.filter(regon=regon, user=self.current_user)

        if self.instance.pk:
            company = company.exclude(pk=self.instance.pk)

        if company.exists():
            raise forms.ValidationError(_("Regon already exists"))

        return regon


class CompanyFilterForm(forms.Form):
    name = forms.CharField(label=_("Name"), required=False)
    nip = forms.CharField(required=False)
    regon = forms.CharField(required=False)

    name.widget.attrs.update({"class": "form-control"})
    nip.widget.attrs.update({"class": "form-control"})
    regon.widget.attrs.update({"class": "form-control"})

    def get_filtered_companies(self, companies_list):
        name = self.cleaned_data["name"]
        nip = self.cleaned_data["nip"]
        regon = self.cleaned_data["regon"]

        if name:
            companies_list = companies_list.filter(name__icontains=name)
        if nip:
            companies_list = companies_list.filter(nip=nip)
        if regon:
            companies_list = companies_list.filter(regon=regon)

        return companies_list

companies/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _

from companies.forms import CompanyFilterForm, CompanyForm
from companies.models import Company
from companies.utils import get_user_company_or_404


@login_required
def list_companies_view(request, my_companies=False):
    if my_companies:
        companies_list = Company.objects.filter(user=request.user, is_my_company=True)
    else:
        companies_list = Company.my_clients.filter(user=request.user)

    filter_form = CompanyFilterForm(request.GET)
    if filter_form.is_valid():
        companies_list = filter_form.get_filtered_companies(companies_list)

    total_companies = companies_list.count()

    paginator = Paginator(companies_list, 10)
    page = request.GET.get("page")
    try:
        companies = paginator.page(page)
    except PageNotAnInteger:
        companies = paginator.page(1)
    except EmptyPage:
        companies = paginator.page(paginator.num_pages)

    context = {
        "companies": companies,
        "total_companies": total_companies,
        "filter_form": filter_form,
    }

    if my_companies:
        context.update({"current_module": "my_companies"})
        template_name = "companies/list_my_companies.html"
    else:
        context.update({"current_module": "companies"})
        template_name = "companies/list_companies.html"

    return render(request, template_name, context)


@login_required
def detail_company_view(request, company_id):
    queryset = Company.objects.select_related("user", "country")
    company = get_object_or_404(queryset, pk=company_id)

    if company.user != request.user:
        raise Http404(_("Company does not exist"))

    context = {"company": company}
    return render(request, "companies/detail_company.html", context)


@login_required
def create_company_view(request, create_my_company=False):
    if request.method != "POST":
        form = CompanyForm(current_user=request.user)
    else:
        form = CompanyForm(data=request.POST, current_user=request.user)
        if form.is_valid():
            company = form.save(commit=False)
            company.user = request.user
            if create_my_company:
                company.is_my_company = True

            company.save()

            if create_my_company:
                return redirect("companies:list_my_companies")

            return redirect("companies:list_companies")

    context = {"form": form, "create_my_company": create_my_company}
    return render(request, "companies/create_company.html", context)


@login_required
def create_company_ajax_view(request, create_my_company=False):
    if request.method != "POST":
        form = CompanyForm(current_user=request.user)
    else:
        form = CompanyForm(data=request.POST, current_user=request.user)
        if form.is_valid():
            company = form.save(commit=False)
            company.user = request.user

            if create_my_company:
                company.is_my_company = True

            company.save()

            return JsonResponse(
                {
                    "success": True,
                    "id": company.id,
                    "name": company.name,
                }
            )
        else:
            return JsonResponse({"success": False, "errors": form.errors})

    context = {"form": form, "create_my_company": create_my_company}
    return render(request, "companies/create_company_ajax.html", context)


@login_required
def replace_company_view(request, company_id):
    company = get_user_company_or_404(company_id, request.user)

    if request.method != "POST":
        form = CompanyForm(instance=company, current_user=request.user)
    else:
        form = CompanyForm(
            instance=company, data=request.POST, current_user=request.user
        )
        if form.is_valid():
            form.save()

            if company.is_my_company:
                return redirect("companies:list_my_companies")

            return redirect("companies:list_companies")

    context = {"company": company, "form": form}
    return render(request, "companies/replace_company.html", context)


@login_required
def delete_company_view(request, company_id):
    company = get_user_company_or_404(company_id, request.user)
    company.delete()

    if company.is_my_company:
        return redirect("companies:list_my_companies")

    return redirect("companies:list_companies")


@login_required
def settings_company_view(request, company_id):
    company = get_user_company_or_404(company_id, request.user)

    context = {"company": company}
    return render(request, "companies/settings_company.html", context)

templates/companies/list_companies.html
{% extends "base.html" %}{% load static %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Kontrahenci</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2">
            <form action="{% url 'companies:list_companies' %}" method='get'>
                <div class="row">
                    <div class="col-md-4 col-lg-5">
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.name.errors }}
                            <label for="{{ filter_form.name.id_for_label }}"
                                   style="font-weight: bold;">Nazwa:</label>
                            {{ filter_form.name }}
                        </div>
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.nip.errors }}
                            <label for="{{ filter_form.nip.id_for_label }}"
                                   style="font-weight: bold;">Nip:</label>
                            {{ filter_form.nip }}
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-5">
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.regon.errors }}
                            <label for="{{ filter_form.regon.id_for_label }}"
                                   style="font-weight: bold;">Regon:</label>
                            {{ filter_form.regon }}
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-2 justify-content-between row justify-content-center gap-2 m-0 mt-2 mt-md-0">
                        <div class="col-12 d-flex align-items-end m-0 p-0">
                            <button class="btn w-100 btn-primary">Szukaj</button>
                        </div>    
                        <div class="col-12 d-flex align-items-end m-0 p-0 mb-2">
                            <a class="btn w-100 btn-outline-primary" href="{% url 'companies:list_companies' %}">Wyczyść</a>
                        </div>
                    </div>
                </div>    
            </form>
        </div>
        <div class="row mt-2">
            {% if companies %}
                <div class="table-responsive">
                    <table class="table table-hover text-center">
                        <thead class="table-light">
                            <tr>
                                <th>Lp.</th>
                                <th>Nazwa</th>
                                <th>NIP</th>
                                <th>Kraj</th>
                                <th>Email</th>
                                <th>Numer telefonu</th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for company in companies %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ company.name }}</td>
                                    <td>{{ company.nip }}</td>
                                    <td>{{ company.country }}</td>
                                    <td>{{ company.email|default_if_none:"-" }}</td>
                                    <td>{{ company.phone_number|default_if_none:"-" }}</td>
                                    <td>
                                        <a href="{% url 'companies:detail_company' company.pk %}">Więcej</a>
                                        <a href="{% url 'companies:replace_company' company.pk %}">Edytuj</a>
                                        <a href="{% url 'companies:delete_company' company.pk %}">Usuń</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-12 d-flex justify-content-left">
                        <b>Brak kontrahenta</b>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="row mt-2">
            <div class="col-12 col-md-auto">
                <a class="btn btn-primary w-100 w-md-auto" href="{% url 'companies:create_company' %}">Dodaj</a>
            </div>
        </div>
        {% if total_companies > 10 %}
            <div class="row">
                <div class="col-12 d-flex justify-content-center">
                    {% include "pagination.html" with page=companies %}
                </div>    
            </div>
        {% endif %}   
    </div>
{% endblock content %}

templates/companies/list_my_companies.html
{% extends "base.html" %}{% load static %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Moje firmy</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2">
            <form action="{% url 'companies:list_my_companies' %}" method='get'>
                <div class="row">
                    <div class="col-md-4 col-lg-5">
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.name.errors }}
                            <label for="{{ filter_form.name.id_for_label }}"
                                   style="font-weight: bold;">Nazwa:</label>
                            {{ filter_form.name }}
                        </div>
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.nip.errors }}
                            <label for="{{ filter_form.nip.id_for_label }}"
                                   style="font-weight: bold;">Nip:</label>
                            {{ filter_form.nip }}
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-5">
                        <div class="fieldWrapper mb-2">
                            {{ filter_form.regon.errors }}
                            <label for="{{ filter_form.regon.id_for_label }}"
                                   style="font-weight: bold;">Regon:</label>
                            {{ filter_form.regon }}
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-2 justify-content-between row justify-content-center gap-2 m-0 mt-2 mt-md-0">
                        <div class="col-12 d-flex align-items-end m-0 p-0">
                            <button class="btn w-100 btn-primary">Szukaj</button>
                        </div>    
                        <div class="col-12 d-flex align-items-end m-0 p-0 mb-2">
                            <a class="btn w-100 btn-outline-primary" href="{% url 'companies:list_my_companies' %}">Wyczyść</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="row mt-2">
            {% if companies %}
                <div class="table-responsive">
                    <table class="table table-hover text-center">
                        <thead class="table-light">
                            <tr>
                                <th>Lp.</th>
                                <th>Nazwa</th>
                                <th>NIP</th>
                                <th>Kraj</th>
                                <th>Email</th>
                                <th>Numer telefonu</th>
                                <th>Opcje</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for company in companies %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ company.name }}</td>
                                    <td>{{ company.nip }}</td>
                                    <td>{{ company.country }}</td>
                                    <td>{{ company.email|default_if_none:"-" }}</td>
                                    <td>{{ company.phone_number|default_if_none:"-" }}</td>
                                    <td>
                                        <a href="{% url 'companies:detail_company' company.pk %}">Więcej</a>
                                        <a href="{% url 'companies:replace_company' company.pk %}">Edytuj</a>
                                        <a href="{% url 'companies:settings_company' company.pk %}">Ustawienia</a>
                                        <a href="{% url 'companies:delete_company' company.pk %}">Usuń</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="row">
                    <div class="col-12 d-flex justify-content-left">
                        <b>Brak firmy</b>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="row mt-2">
            <div class="col-12 col-md-auto">
                <a class="btn btn-primary w-100 w-md-auto" href="{% url 'companies:create_my_company' %}">Dodaj</a>
            </div>
        </div>
        {% if total_companies > 10 %}
            <div class="row">
                <div class="col-12 d-flex justify-content-center">
                    {% include "pagination.html" with page=companies %}
                </div>    
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/companies/settings_company.html
{% extends "base.html" %}{% load static %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:list_my_companies' %}">Moje firmy</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'companies:detail_company' company.pk %}">{{ company.name }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Ustawienia</li>
                </ol>
            </nav>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-6 d-flex justify-content-center flex-md-row flex-column gap-2">
                <a class="btn btn-primary w-100 w-md-auto" href="{% url 'summary_recipients:list_summary_recipients' company.pk %}">Odbiorcy faktur</a>
                <a class="btn btn-primary w-100 w-md-auto" href="{% url 'accountants:list_accountants' company.pk %}">Księgowość</a>
            </div>
        </div>
        <div class="row mt-3 justify-content-center">
            <div class="col-md-6 d-flex justify-content-center flex-md-row flex-column">
                <a class="btn btn-secondary" href="{% url 'companies:list_my_companies' %}">Powrót</a>
            </div>
        </div>
    </div>
{% endblock content %}