base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from base import urls_api
from invoices.views import index_view

urlpatterns = [
    path("", index_view, name="index"),
    path("admin/", admin.site.urls),
    path("api/", include(urls_api)),
    path("api-token-auth/", obtain_auth_token),
    path("companies/", include("companies.urls")),
    path("countries/", include("countries.urls")),
    path("currencies/", include("currencies.urls")),
    path("invoices/", include("invoices.urls")),
    path("items/", include("items.urls")),
    path("users/", include("users.urls")),
    path("vat_rates/", include("vat_rates.urls")),
    path("reports/", include("reports.urls")),
    path("accountants/", include("accountants.urls")),
    path("summary_recipients/", include("summary_recipients.urls")),
    path("persons/", include("persons.urls")),
    path("faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="privacy_policy.html"),
        name="privacy_policy",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companies/urls.py
from django.urls import path

from companies.views import (
    create_company_ajax_view,
    create_company_view,
    delete_company_view,
    detail_company_view,
    list_companies_view,
    replace_company_view,
    settings_company_view,
)

app_name = "companies"
urlpatterns = [
    path("", list_companies_view, name="list_companies"),
    path(
        "my_companies/",
        list_companies_view,
        name="list_my_companies",
        kwargs={"my_companies": True},
    ),
    path("<int:company_id>/", detail_company_view, name="detail_company"),
    path("create/", create_company_view, name="create_company"),
    path("create_ajax/", create_company_ajax_view, name="create_company_ajax"),
    path(
        "create_my_company/",
        create_company_view,
        name="create_my_company",
        kwargs={"create_my_company": True},
    ),
    path(
        "create_my_company_ajax/",
        create_company_ajax_view,
        name="create_my_company_ajax",
        kwargs={"create_my_company": True},
    ),
    path("replace/<int:company_id>/", replace_company_view, name="replace_company"),
    path("delete/<int:company_id>/", delete_company_view, name="delete_company"),
    path(
        "<int:company_id>/settings_company/",
        settings_company_view,
        name="settings_company",
    ),
]

currencies/urls.py
from django.urls import path

from currencies.views import (
    create_currency_ajax_view,
    create_currency_view,
    delete_currency_view,
    list_currencies_view,
    replace_currency_view,
)

app_name = "currencies"
urlpatterns = [
    path("", list_currencies_view, name="list_currencies"),
    path("create/", create_currency_view, name="create_currency"),
    path("create_ajax/", create_currency_ajax_view, name="create_currency_ajax"),
    path("replace/<int:currency_id>/", replace_currency_view, name="replace_currency"),
    path("delete/<int:currency_id>/", delete_currency_view, name="delete_currency"),
]

invoice_manager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

invoices/urls.py
from django.urls import path

from invoices.views import (
    create_buy_invoice_view,
    create_sell_invoice_view,
    create_sell_person_invoice_view,
    create_sell_person_to_client_invoice_view,
    delete_invoice_view,
    detail_invoice_view,
    duplicate_company_invoice_view,
    duplicate_individual_invoice_view,
    list_invoices_view,
    pdf_invoice_view,
    replace_buy_invoice_view,
    replace_sell_invoice_view,
    replace_sell_person_to_client_invoice_view,
)

app_name = "invoices"
urlpatterns = [
    path("", list_invoices_view, name="list_invoices"),
    path("<int:invoice_id>/", detail_invoice_view, name="detail_invoice"),
    path("create_sell_invoice/", create_sell_invoice_view, name="create_sell_invoice"),
    path("create_buy_invoice/", create_buy_invoice_view, name="create_buy_invoice"),
    path(
        "create_sell_person_invoice/",
        create_sell_person_invoice_view,
        name="create_sell_person_invoice",
    ),
    path(
        "create_sell_person_to_client_invoice/",
        create_sell_person_to_client_invoice_view,
        name="create_sell_person_to_client_invoice",
    ),
    path(
        "duplicate_company_invoice/<int:invoice_id>/",
        duplicate_company_invoice_view,
        name="duplicate_company_invoice",
    ),
    path(
        "duplicate_individual_invoice/<int:invoice_id>/",
        duplicate_individual_invoice_view,
        name="duplicate_individual_invoice",
    ),
    path(
        "replace_sell_invoice/<int:invoice_id>/",
        replace_sell_invoice_view,
        name="replace_sell_invoice",
    ),
    path(
        "replace_sell_person_to_client_invoice/<int:invoice_id>/",
        replace_sell_person_to_client_invoice_view,
        name="replace_sell_person_to_client_invoice",
    ),
    path(
        "create_correction_invoice/<int:invoice_id>/",
        replace_sell_invoice_view,
        name="create_correction_invoice",
        kwargs={"create_correction": True},
    ),
    path(
        "create_correction_person_to_client_invoice/<int:invoice_id>/",
        replace_sell_person_to_client_invoice_view,
        name="create_correction_person_to_client_invoice",
        kwargs={"create_correction": True},
    ),
    path(
        "replace_buy_invoice/<int:invoice_id>/",
        replace_buy_invoice_view,
        name="replace_buy_invoice",
    ),
    path("delete/<int:invoice_id>/", delete_invoice_view, name="delete_invoice"),
    path("pdf/<int:invoice_id>/", pdf_invoice_view, name="pdf_invoice"),
]

items/urls.py
from django.urls import path

from items.views import create_item_view, delete_item_view, replace_item_view

app_name = "items"
urlpatterns = [
    path("create/<int:invoice_id>/", create_item_view, name="create_item"),
    path("replace/<int:item_id>/", replace_item_view, name="replace_item"),
    path("delete/<int:item_id>/", delete_item_view, name="delete_item"),
]

persons/urls.py
from django.urls import path

from persons.views import (
    create_person_ajax_view,
    create_person_view,
    delete_person_view,
    detail_person_view,
    list_persons_view,
    replace_person_view,
)

app_name = "persons"
urlpatterns = [
    path("", list_persons_view, name="list_persons"),
    path("detail/<int:person_id>", detail_person_view, name="detail_person"),
    path("create/", create_person_view, name="create_person"),
    path("create_ajax/", create_person_ajax_view, name="create_person_ajax"),
    path("replace/<int:person_id>/", replace_person_view, name="replace_person"),
    path("delete/<int:person_id>/", delete_person_view, name="delete_person"),
]

invoices/models.py
import decimal

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from num2words import num2words

from companies.models import Company
from currencies.models import Currency, ExchangeRate
from invoices.managers import InvoiceQuerySet
from persons.models import Person
from users.models import User


class Invoice(models.Model):
    INVOICE_SALES = 0
    INVOICE_PURCHASE = 1

    INVOICE_TYPES = (
        (INVOICE_SALES, _("Sales")),
        (INVOICE_PURCHASE, _("Purchase")),
    )

    BANK_TRANSFER = 0
    CASH_PAYMENT = 1

    PAYMENT_METHOD = (
        (BANK_TRANSFER, _("Transfer")),
        (CASH_PAYMENT, _("Cash")),
    )

    WEEKLY = 0
    BIWEEKLY = 1
    MONTHLY = 2
    THREE_MONTH = 3

    invoice_number = models.CharField(
        verbose_name=_("Invoice number"), max_length=30, null=True, blank=True
    )
    invoice_type = models.IntegerField(
        verbose_name=_("Invoice type"), choices=INVOICE_TYPES
    )
    company = models.ForeignKey(
        Company,
        verbose_name=_("Company"),
        on_delete=models.CASCADE,
        related_name="invoices",
        null=True,
        blank=True,
    )
    person = models.ForeignKey(
        Person,
        verbose_name=_("Person"),
        on_delete=models.CASCADE,
        related_name="invoices",
        null=True,
        blank=True,
    )
    is_recurring = models.BooleanField(verbose_name=_("Recurring"), default=False)
    is_last_day = models.BooleanField(
        verbose_name=_("Last day in month"), default=False
    )
    is_settled = models.BooleanField(verbose_name=_("Settled"), default=False)
    settlement_date = models.DateField(
        verbose_name=_("Settlement date"), default=timezone.now, editable=True
    )
    create_date = models.DateField(
        verbose_name=_("Create date"), default=timezone.now, editable=True
    )
    sale_date = models.DateField(
        verbose_name=_("Sale date"), default=timezone.now, editable=True
    )
    payment_date = models.DateField(
        verbose_name=_("Payment date"), default=timezone.now, editable=True
    )
    payment_method = models.IntegerField(
        verbose_name=_("Payment method"), choices=PAYMENT_METHOD, null=True, blank=True
    )
    currency = models.ForeignKey(
        Currency,
        verbose_name=_("Currency"),
        on_delete=models.CASCADE,
        null=True,
        related_name="invoices",
    )
    account_number = models.CharField(
        verbose_name=_("Account number"), max_length=50, null=True, blank=True
    )
    client = models.ForeignKey(
        Company,
        verbose_name=_("Client"),
        on_delete=models.CASCADE,
        related_name="client_invoices",
        null=True,
        blank=True,
    )
    invoice_file = models.FileField(
        verbose_name=_("Invoice file"), null=True, blank=True
    )
    is_paid = models.BooleanField(verbose_name=_("Paid"), default=False)
    net_amount = models.DecimalField(
        verbose_name=_("Net amount"), max_digits=9, decimal_places=2, default=0
    )
    gross_amount = models.DecimalField(
        verbose_name=_("Gross_amount"), max_digits=9, decimal_places=2, default=0
    )

    objects = InvoiceQuerySet.as_manager()

    class Meta:
        verbose_name_plural = _("invoices")
        ordering = ["-sale_date"]
        unique_together = ["invoice_number", "company"]

    def __str__(self):
        return self.invoice_number or f'{_("Recurring")}'

    def calculate_net_amount(self):
        net_sum = 0
        for item in self.items.all():
            net_sum = net_sum + item.net_amount
        return net_sum

    @property
    def tax_amount(self):
        tax_sum = 0
        for item in self.items.all():
            tax_sum = tax_sum + item.tax_amount
        return tax_sum

    def calculate_gross_amount(self):
        gross_sum = decimal.Decimal("0")
        for item in self.items.all():
            gross_sum = gross_sum + item.gross_amount
        return gross_sum

    @property
    def sell_rate_in_pln(self):
        if self.currency.code == settings.BASE_CURRENCY_CODE:
            return decimal.Decimal("1.00")

        try:
            exchange_rate = ExchangeRate.objects.get(
                currency=self.currency, date=self.sale_date
            )
            return exchange_rate.sell_rate
        except ExchangeRate.DoesNotExist:
            return None

    @property
    def is_sell(self):
        return self.invoice_type == Invoice.INVOICE_SALES

    @property
    def has_item_with_vat(self):
        return self.items.filter(vat__rate__gt=0).exists()

    @property
    def has_items(self):
        return self.items.exists()

    @property
    def has_correction_invoice(self):
        return hasattr(self, "correction_invoice_relation")

    def get_html_for_pdf(self):
        items = self.items.all()

        template_path = "invoices/pdf_invoice.html"

        gross_amount = num2words(
            self.gross_amount,
            lang="pl",
            to="currency",
            currency=self.currency.code.upper(),
        )

        context = {
            "invoice": self,
            "items": items,
            "gross_amount": gross_amount,
        }

        html = render_to_string(template_path, context)
        return html


class Year(models.Model):
    year = models.PositiveSmallIntegerField(
        verbose_name=_("Year"),
    )
    user = models.ForeignKey(
        User, verbose_name=_("User"), on_delete=models.CASCADE, null=True
    )

    class Meta:
        verbose_name_plural = _("years")
        ordering = ["-year"]
        unique_together = ["year", "user"]

    def __str__(self):
        return str(self.year)


def get_user_from_invoice(invoice_instance):
    if invoice_instance.company:
        return invoice_instance.company.user
    elif invoice_instance.person:
        return invoice_instance.person.user
    return None


def cleanup_orphaned_year(user, year_value):
    if user and year_value:
        if not Invoice.objects.filter(
            Q(company__user=user) | Q(person__user=user), sale_date__year=year_value
        ).exists():
            Year.objects.filter(year=year_value, user=user).delete()


@receiver(pre_save, sender=Invoice)
def store_old_sale_date(sender, instance, **kwargs):
    if instance.pk:
        try:
            old_instance = sender.objects.get(pk=instance.pk)
            instance._old_sale_date = old_instance.sale_date
        except sender.DoesNotExist:
            instance._old_sale_date = None
    else:
        instance._old_sale_date = None


@receiver(post_save, sender=Invoice)
def handle_year_after_save(sender, instance, **kwargs):
    user = get_user_from_invoice(instance)
    if not user:
        return

    Year.objects.get_or_create(year=instance.sale_date.year, user=user)

    old_sale_date = getattr(instance, "_old_sale_date", None)
    if old_sale_date:
        old_year = old_sale_date.year
        new_year = instance.sale_date.year

        if old_year != new_year:
            cleanup_orphaned_year(user, old_year)


@receiver(post_delete, sender=Invoice)
def handle_year_after_delete(sender, instance, **kwargs):
    user = get_user_from_invoice(instance)
    year_to_check = instance.sale_date.year
    cleanup_orphaned_year(user, year_to_check)


class CorrectionInvoiceRelation(models.Model):
    invoice = models.OneToOneField(
        Invoice,
        verbose_name=_("Invoice"),
        on_delete=models.CASCADE,
        related_name="original_invoice_relation",
    )
    correction_invoice = models.OneToOneField(
        Invoice,
        verbose_name=_("Correction Invoice"),
        on_delete=models.CASCADE,
        related_name="correction_invoice_relation",
    )

    class Meta:
        verbose_name_plural = _("correction invoices relation")

    def __str__(self):
        return (
            f"{self.invoice.invoice_number}, {self.correction_invoice.invoice_number}"
        )

templates/invoices/detail_sell_invoice.html
{% extends "base.html" %}{% load static %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                   <li class="breadcrumb-item">
                        <a href="{% url 'index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"></path>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'invoices:list_invoices' %}">Faktura</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {% if not invoice.is_recurring %}
                            {{ invoice.invoice_number }}
                        {% else %}
                            <span>Faktura cykliczna</span>
                        {% endif %}
                    </li>
                </ol>
            </nav>
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Typ faktury:</div>
            <div class="col-4">{{ invoice.get_invoice_type_display }}</div>
        </div>
        {% if not invoice.correction_invoice_relation %}
            <div class="row mb-2">
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Cykliczność:</div>
                <div class="col-4">
                    {% if invoice.is_recurring %}
                        <span>Tak</span>
                    {% else %}
                        <span>Nie</span>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <div class="row mb-2">
            {% if invoice.company %}
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Sprzedawca:</div>
                <div class="col-4">{{ invoice.company }}</div>
            {% else%}
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Sprzedawca:</div>
                <div class="col-4">{{ invoice.person }}</div>
            {% endif %}
        </div>
        <div class="row mb-2">
            {% if invoice.client %}
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Nabywca:</div>
                <div class="col-4">{{ invoice.client }}</div>
            {% else%}
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Nabywca:</div>
                <div class="col-4">{{ invoice.person }}</div>
            {% endif %}
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Data utworzenia:</div>
            <div class="col-4">{{ invoice.create_date| date:"d.m.Y" }}</div>
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Data sprzedaży:</div>
            <div class="col-4">{{ invoice.sale_date| date:"d.m.Y" }}</div>
        </div>
        {% if not invoice.correction_invoice_relation and invoice.is_recurring %}
            <div class="row mb-2">
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Data sprzedaży to ostatni dzień miesiąca:</div>
                <div class="col-4">
                    {% if invoice.is_last_day %}
                        <span>Tak</span>
                    {% else %}
                        <span>Nie</span>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Data płatności:</div>
            <div class="col-4">{{ invoice.payment_date| date:"d.m.Y" }}</div>
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Sposób płatności:</div>
            <div class="col-4">{{ invoice.get_payment_method_display }}</div>
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Waluta:</div>
            <div class="col-4">{{ invoice.currency }}</div>
        </div>
        <div class="row mb-2">
            <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Numer konta:</div>
            {% if invoice.account_number %}
                <div class="col-4">{{ invoice.account_number }}</div>
            {% else %}
                <div class="col-4">-</div>
            {% endif %}
        </div>
        {% if not invoice.is_recurring %}
            <div class="row mb-2">
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Opłacona:</div>
                {% if invoice.is_paid %}
                    <div class="col-4">Tak</div>
                {% else %}
                    <div class="col-4">Nie</div>
                {% endif %}
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-6 text-md-end" style="font-weight: bold;">Rozliczona:</div>
                <div class="col-4">
                    {% if invoice.is_settled %}
                        <span>Tak</span>
                    {% else %}
                        <span>Nie</span>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <div class="row mt-3 justify-content-center">
            <div class="col-12 col-md-auto d-flex flex-column flex-md-row gap-2">
                {% if not invoice.is_settled %}
                    {% if invoice.company %}
                        <a class="btn btn-primary w-md-auto" href="{% url 'invoices:replace_sell_invoice' invoice.pk %}">Edytuj</a>
                    {% else %}
                        <a class="btn btn-primary w-md-auto" href="{% url 'invoices:replace_sell_person_to_client_invoice' invoice.pk %}">Edytuj</a>
                    {% endif %}    
                    <a class="btn btn-danger w-md-auto" href="{% url 'invoices:delete_invoice' invoice.pk %}">Usuń</a>
                {% endif %}
                {% if not invoice.is_recurring and invoice.has_items and not invoice.has_correction_invoice %}
                    {% if invoice.company %}
                        <a class="btn btn-secondary w-md-auto" href="{% url 'invoices:duplicate_company_invoice' invoice.pk %}">Duplikuj</a>
                    {% else %}
                        <a class="btn btn-secondary w-md-auto" href="{% url 'invoices:duplicate_individual_invoice' invoice.pk %}">Duplikuj</a>
                    {% endif %}
                {% endif %}
                {% if invoice.company %}
                    {% if not invoice.is_recurring and not invoice.original_invoice_relation and not invoice.correction_invoice_relation and invoice.has_items %}
                        <a class="btn btn-primary w-md-auto" href="{% url 'invoices:create_correction_invoice' invoice.pk %}">Dodaj fakturę korygującą</a>
                    {% endif %}
                {% else %}
                    {% if not invoice.is_recurring and not invoice.original_invoice_relation and not invoice.correction_invoice_relation %}
                        <a class="btn btn-primary w-md-auto" href="{% url 'invoices:create_correction_person_to_client_invoice' invoice.pk %}">Dodaj fakturę korygującą</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="row mt-2 text-center" style="color: red">
                {% if invoice.original_invoice_relation %}
                    <p>Do faktury istnieje <a target="_blank" href="{% url 'invoices:detail_invoice' invoice.original_invoice_relation.correction_invoice.pk %}">faktura korygująca</a></p>
                {% endif %}
            </div>
        </div>
        <div class="row mt-2">
            {% if invoice.items.exists %}
                <div class="table-responsive">
                    <table class="table table-hover text-center mt-2">
                        <thead class="table-light">
                            <tr>
                                <th>Lp.</th>
                                <th style="width: 500px;">Nazwa</th>
                                <th>PKWiU</th>
                                <th>Ilość</th>
                                <th>Cena netto</th>
                                <th>Wartość netto</th>
                                <th>VAT</th>
                                <th>Kwota VAT</th>
                                <th>Wartość brutto</th>
                                {% if not invoice.is_settled %}
                                    <th>Opcje</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% for item in invoice.items.all %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td style="width: 500px;">{{ item.name }}</td>
                                    <td>
                                        {% if item.pkwiu %}
                                            {{ item.pkwiu }}
                                        {% else %}
                                            <span>-</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ item.amount }}</td>
                                    <td>{{ item.net_price|floatformat:"2g" }}</td>
                                    <td>{{ item.net_amount|floatformat:"2g" }}</td>
                                    <td>
                                        {% if item.vat %}
                                            {{ item.vat }} %
                                        {% else %}
                                            <span>ZW</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ item.tax_amount|floatformat:"2g" }}</td>
                                    <td>{{ item.gross_amount|floatformat:"2g" }}</td>
                                    <td>
                                        {% if not invoice.is_settled %}
                                            <a href="{% url 'items:replace_item' item.pk %}?next={% url 'invoices:detail_invoice' invoice.pk %}">Edytuj</a>
                                            <a href="{% url 'items:delete_item' item.pk %}?next={% url 'invoices:detail_invoice' invoice.pk %}">Usuń</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
            <div class="row">
                <div class="col-12 d-flex justify-content-left">
                    <b>Brak pozycji do faktury </b>
                </div>
            </div>
            {% endif %}
        </div>
        {% if not invoice.is_settled %}
            <div class="row mt-2">
                <div class="col-12 col-md-auto">
                    <a class="btn btn-primary w-100 w-md-auto" href="{% url 'items:create_item' invoice.pk %}">Dodaj</a>
                </div>
            </div>
        {% endif %}
        <div class="row mt-2 justify-content-center">
            <div class="col-12 col-md-auto d-flex flex-column flex-md-row gap-2">
                {% if invoice.items.exists and not invoice.is_recurring %}
                    <a class="btn btn-success w-md-auto" href="{% url 'invoices:pdf_invoice' invoice.pk %}" target="_blank" rel="noopener noreferrer">Faktura pdf</a>
                {% endif %}
                <a class="btn btn-secondary w-md-auto" href="{% url 'invoices:list_invoices' %}">Powrót</a>
            </div>
        </div>
    </div>
{% endblock content %}